apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-frontend-ingress
spec:
  rules:
  # - host: localhost
  #   http:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-frontend-service
            port:
              number: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  selector:
    app: web-frontend
  ports:
    - port: 9080
      targetPort: 3000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-frontend-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300 
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-deployment
  labels:
    app: web-frontend
spec:
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          # image: judahlit/moodify_web_frontend:latest
          image: k3d-moodify:5000/web_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 350m
          env:
            - name: NUXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-api-key
            - name: NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-auth-domain
            - name: NUXT_PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-project-id
            - name: NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-storage-bucket
            - name: NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-messaging-sender-id
            - name: NUXT_PUBLIC_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-app-id
            - name: NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-measurement-id
            - name: NUXT_PUBLIC_GATEWAY_URL
              value: 
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3