apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  selector:
    app: web-frontend
  ports:
    - port: 9099
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-deployment
  labels:
    app: web-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          # image: judahlit/moodify_web_frontend:latest
          image: k3d-moodify:5000/web_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-api-key
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-auth-domain
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-project-id
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-storage-bucket
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-messaging-sender-id
            - name: FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-app-id
            - name: FIREBASE_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: web-frontend-secret
                  key: firebase-measurement-id
            - name: GATEWAYURL
              value: "http://moodify-gateway-service:8080"
