name: Build and Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Create Firebase credentials file
        run: |
          echo "${{ secrets.FIREBASE_CREDS }}" > ./firebase-auth-creds.json

      - name: Build and test application
        env:
          CORS_ALLOWED_ORIGIN: http://localhost:3000
          GOOGLE_APPLICATION_CREDENTIALS: /firebase-auth-creds.json
          GOOGLE_CLOUD_PROJECT_ID: moodify-web-frontend
          SONG_SERVICE_URL: http://localhost:8081
          ANALYTICS_SERVICE_URL: http://localhost:8082
        run: gradle build --no-daemon --info

      - name: Upload Test Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}/build/reports/tests/test/*
